# Generated by Django 3.0.3 on 2020-04-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='unit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='quanlity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount',
            field=models.IntegerField(),
        ),
    ]
