# Generated by Django 3.0.3 on 2020-04-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0002_auto_20200416_2256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userapp',
        ),
    ]
